# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('Student', 'Student'), ('Teacher', 'Teacher')], help_text='Role', max_length=10, null=True)),
                ('enroll_number', models.PositiveIntegerField(help_text='Enroll Number', null=True, unique=True)),
            ],
        ),
    ]
